name: sprinter_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
